### ISSUE TITLE
Array of custom sub-structs

### ISSUE THREAD

**Issue by christophfroehlich** [PickNikRobotics/generate_parameter_library#140]
Is it somehow possible to declare an array of a custom sub-structure? Or how could the library be extended in this way?

Something like

```yaml
cpp_name_space:
  sub_array:
    sub_struct:
      a_parameter: {
        type: double
      }
      another_parameter: {
        type: double
      }
```
and
```yaml
  ros__parameters:
    sub_array:
      - a_parameter: 1.
        another_parameter: 2.0
      - a_parameter: 2.
        another_parameter: 3.0
```

used as `params.sub_array.at(0).a_parameter`
