### ISSUE TITLE
Feature request: Unsigned integers

### ISSUE THREAD

**Issue by Timple** [PickNikRobotics/generate_parameter_library#172]
Would it make sense to allow `uint` as a type, next to `int`?

It would reduce this:
```yaml
    buttons:
      type: int_array
      validation:
        lower_element_bounds<>: 0
```
To this:

```yaml
    buttons:
      type: uint_array
```
So internally it could do a sanity check on the sign and (for c++) cast to an `uint32_t`.
