### ISSUE TITLE
Parameter namespaces that map to other parameters

### ISSUE THREAD

**Issue by tylerjw** [PickNikRobotics/generate_parameter_library#18]
### Use Case

Currently, in ros2_control's JTC there is this pattern:

```yaml
joints:
  - A
  - B
pid:
  A:
    p: 0.2
    i: 0.4
    d: 0.0
  B:
    p: 0.2
    i: 0.3
    d: 0.1
```

The basic idea is that there is some string array parameter, in this case joint names, that become part of the namespace of other parameters. This is done in two separate places in JTC and seems to be a generally useful feature.

### Design

Make namespaces that come from other string-array parameters a first-class feature of the declarative yaml symtax for parameters.

Because the names of these depend on other parameters they should always be handled after all other parameters as the second type of parameter so updates to the string array or the map can be checked correctly.

## YAML syntax

For the yaml syntax use the name `___map_<string_array_parameter_name>` to represent the special type. Here is an example:

```yaml
joints: {
  type: string_array
}
pid:
  rate: {
    type: double
  }
  ___map_joints:
    p: {
      type: double
    }
    i: {
      type: double
    }
    d: {
      type: double
    }
```

## C++ Struct

The structure that results from the example is:

```cpp
std::vector<std::string> joints;
struct PID {
  double rate;
  struct JOINTS_MAP_VALUE {
    double p;
    double i;
    double d;
  };
  std::map<std::string, JOINTS_MAP_VALUE> joints_map;
};
PID pid;
```

## Declaring/Getting Parameters

`declare_params` method will be split into two sections, the first will declare, get, and validate all normal non-refering parameters then it will declare, get, and validate and reffering types. This is because the names needed to declare the referring types can only be known after the normal types have been read.

## Special Validation

1. Name in `joints` does not exist as sub-name of `pid`:
  - this is only an error if all real parameters don't have defaults and require the user to set these parameters
  - the normal way declaration works covers this
2. Sub-name of `pid` does not exist in `joints`:
  - This is the same as the user setting a parameter that wasn't declared

## Update

Updating is similar to declaring/getting in that all mapped parameters should be handled after all normal parameters.

If the base string_array (`joints` in the example) was modified by the update we need to handle it.
1. Value was removed from `joints`:
  - remove the entry from the c++ map
  - undeclare parameter name
2. Value was added to 'joints':
  - declare parameters

After all the updating of the structure is done (declaration) there should be the normal checking if any of the declared names have been updated and get/validate them.
