### ISSUE TITLE
Statically Sized Parameters

### ISSUE THREAD

**Issue by jcarpinelli-bdai** [PickNikRobotics/generate_parameter_library#190]
Is it possible to configure `std::array`-valued parameters for fixed-size definitions? For example, for Cartesian stiffness gains, I'm currently using...

```yaml
cartesian_impedance_parameters:
  stiffness: 
    x: {
        type: double,
    }, 
    y: {
        type: double,
    },
    ...
```

It may be nice to have a single parameter for stiffness gains, but still have stack-allocated values. For example...

```yaml
cartesian_impedance_parameters:
  stiffness: {
    type: double_array_fixed_06,
  }
```

**Do you agree this feature does not currently exist, but may be a nice feature to have?**
