### ISSUE TITLE
Inheritance?

### ISSUE THREAD

**Issue by edwardribbit** [PickNikRobotics/generate_parameter_library#193]
This is an idea and I don't know if it's possible to implement
Is there a simple way to select from a set of variables like inheritance in the code?

```
A:
  my_var:
    my_int: {type: int}
B:
  my_var:
    my_int: {type: int}
```

Use case (pseudocode)

```
auto my_var;
if(A){
  my_var = A.my_var;
}else if(B){
  my_var = B.my_var;
}

print(my_var.my_int)
```
