### ISSUE TITLE
Build hangs in Dockerized Bitbucket CI with coverage flags

### ISSUE THREAD

**Issue by fnivek** [PickNikRobotics/generate_parameter_library#201]
My builds hang under some rather specific conditions:

- Bitbucket docker based CI
- Base image docker:git
- Custom image built inside a docker:git container
- Custom container run from inside docker:git container
- Having more than the first two parameters in my yaml
- building with cmake coverage flags
- tag 0.3.8

Most of the time the error is a timeout after two hours but once I had an error of out of memory. Builds work just fine on my local machine and in the same container built in the CI pipeline, but not in bitbucket's CI pipeline. Any ideas what might be causing it, or ways to debug it?

CMake:
```CMake
find_package(generate_parameter_library REQUIRED)
generate_parameter_library(<lib_name>_parameters src/params.yaml)
...
target_link_libraries(<lib_name> ... <lib_name>_parameters)
```

params.yaml:
```yaml
<lib_name>:
  joints: {
    type: string_array,
    description: "List of joints.",
    read_only: true
  }
  frame_id: {
    type: string,
    description: "The frame id.",
    read_only: true
  }
  xx: {
    type: double,
    description: "The xx.",
    read_only: true,
    default_value: 1.0
  }
```

Build command:
`colcon build --cmake-args -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} --coverage" -DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} --coverage"`
