### ISSUE TITLE
Including Other Parameters in Validator Inputs

### ISSUE THREAD

**Issue by jcarpinelli-bdai** [PickNikRobotics/generate_parameter_library#217]
Is there any way to use other parameter values as inputs to custom validators? For example, say we have URDF and SRDF parameters, and we want to make sure they are consistent with one another in a custom validator. 
```
robot_description_parameters:
  urdf: 
    type: string
  srdf:
    type: string
    validation:
      "robot_description_validators::srdf_compatible": [urdf]
```
